var SINGLE_PARAMETERS = 
'{'
+ '  "dqn_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 64,'
+ '    "buffer_size": 100000,'
+ '    "lr": 0.0001,'
+ '    "epsilon_steps": 20000,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "ddpg_parameters": {'
+ '    "gamma": 0.9,'
+ '    "batch_size": 64,'
+ '    "buffer_size": 100000,'
+ '    "actor_lr": 0.0001,'
+ '    "critic_lr": 0.001,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "agent_parameters": {'
+ '    "hidden_dim": 64'
+ '  },'
+ '  "sim_parameters": {'
+ '    "state_type": "relative",'
+ '    "action_type": "continuous",'
+ '    "reward_type": "positive_followball",'
+ '    "algorithm": "dqn",'
+ '    "frame_skip": 2,'
+ '    "robot": [false, false, false, false, true]'
+ '  }'
+ '}';

var MULTI_PARAMETERS = 
'{'
+ '  "iql_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 64,'
+ '    "buffer_size": 100000,'
+ '    "lr": 0.0001,'
+ '    "epsilon_steps": 20000,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "qmix_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 64,'
+ '    "buffer_size": 100000,'
+ '    "lr": 0.00005,'
+ '    "epsilon_steps": 20000,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "agent_parameters": {'
+ '    "hidden_dim": 64'
+ '  },'
+ '  "sim_parameters": {'
+ '    "state_type": "relative",'
+ '    "action_type": "discrete",'
+ '    "reward_type": "positive_followball",'
+ '    "algorithm": "iql",'
+ '    "frame_skip": 2,'
+ '    "robot": [true, true, true, true, true]'
+ '  }'
+ '}';